
POST http://localhost:8080/search 
Content-Type: application/json

{
    "query":"*",
    "topk": 10
}

###

POST http://localhost:8080/modify HTTP/2.0
Content-Type: application/json
Accept-Encoding: gzip

[
    {
        "overwrite":true,
        "delete": false,
        "doc": 
            {
                "thread_id": 274,
                "title": "test",
                "text": "test",
                "node_id": 0,
                "needModer": 0,
                "post_date": 0
            }
    }
]

###

POST http://localhost:8080/drop HTTP/2.0


###

curl -d '{
    "query":"Вязание крючком для начинающих. Видеокурс из 30 уроков",
    "topk": 5
}' -H "Content-Type: application/json" -X POST http://localhost:8080/
