# POST http://0.0.0.0:8080/ HTTP/2.0
POST http://localhost:8080/search HTTP/2.0
Content-Type: application/json

{
    "query":"thread_id:1327",
    "topk": 5
}

###

POST http://localhost:8080/modify HTTP/2.0
Content-Type: application/json

{
    "overwrite":false,
    "delete": true,
    "post": 
        {
            "thread_id": 1327,
            "title": "",
            "text": "",
            "node_id": 0,
            "needModer": 0,
            "post_date": 0
        }
}

###

curl -d '{
    "query":"Вязание крючком для начинающих. Видеокурс из 30 уроков",
    "topk": 5
}' -H "Content-Type: application/json" -X POST http://localhost:8080/
