# POST http://0.0.0.0:8080/ HTTP/2.0
POST http://188.120.254.29:8080/ HTTP/2.0
Content-Type: application/json

{
    "query":"(Тренинг Kak Bлюбитьcя и нe пoтеpять ceбя) AND (node_id:15)",
    "topk": 5
}


GET http://188.120.254.29:8080/ HTTP/2.0


curl -d '{
    "query":"Вязание крючком для начинающих. Видеокурс из 30 уроков",
    "topk": 5
}' -H "Content-Type: application/json" -X POST http://localhost:8080/
